language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t mlossmann/client-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mlossmann/client-react npm run test -- --coverage

after_success:
  - docker build -t mlossmann/multi-client ./client
  - docker build -t mlossmann/multi-nginx ./nginx
  - docker build -t mlossmann/multi-server ./server
  - docker build -t mlossmann/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mlossmann/multi-client
  - docker push mlossmann/multi-nginx
  - docker push mlossmann/multi-server
  - docker push mlossmann/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-237387071766"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
